# Cross build profile for SuperH4.

XBPS_TARGET_MACHINE="sh4"
XBPS_TARGET_QEMU_MACHINE="sh4"
XBPS_CROSS_TRIPLET="sh4-linux-gnu"
XBPS_CROSS_CFLAGS="-march=sh4"
XBPS_CROSS_CXXFLAGS="$XBPS_CROSS_CFLAGS"
XBPS_CROSS_FFLAGS="$XBPS_CROSS_CFLAGS"
XBPS_CROSS_RUSTFLAGS="--sysroot=${XBPS_CROSS_BASE}/usr"
XBPS_CROSS_RUST_TARGET="sh4-unknown-linux-gnu"
